---
# Ansible playbook to deploy Puppet Agent on a server and ensure its running
- name: deploy Puppet Agent
  hosts: all
  user: root
  var_files:
    - "vars/{{ ansible_os_family }}.yml"
  roles: common