---
# Ansible playbook to deploy Puppet Agent on a server and ensure its running
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Puppet Agent is started in noop mode
  copy:
    dest=/etc/sysconfig/pe-puppet
    content="EXTRA_OPTIONS=--noop"

- include: redhat.yml
  when: ansible_os_family=="RedHat"

- include: ubuntu.yml
  when: ansible_os_family=="Ubuntu"

- include: debian.yml
  when: ansible_os_family=="Debian"

- include: solaris.yml
  when: ansible_os_family=="Solaris"

- include: aix.yml
  when: ansible_os_family=="AIX"