---
# Ansible playbook to deploy Puppet Agent on a server and ensure its running
- name: Ensure Puppet Agent install directory
  file:
    path=/root/puppetinstall
    state=directory

- name: Ensure Puppet install log
  file:
    path=/root/puppetinstall/puppetagentinstall.log
    state=touch

- name: Ensure PE tarball present
  get_url:
    url=https://s3.amazonaws.com/pe-builds/released/{{ pe_version }}/{{ pe_installer }}.tar.gz
    dest=/root/puppetinstall/peinstaller.tar.gz
    force=no

- name: Ensure Puppet untar'd to install directory
  unarchive: 
    copy=no
    src=/root/puppetinstall/peinstaller.tar.gz
    dest=/root/puppetinstall

- name: Ensure Puppet Agent answer file
  template:
    src="../files/puppetagent.answers.j2"
    dest=/root/puppetinstall/puppetagent.answers

- name: Ensure Puppet repo files 
  template:
    src="../files/tmo_puppet.repo"
    dest=/etc/yum.repos.d/tmo_puppet.repo

- name: Ensure pre-req system packages installed
  yum:
    name={{ item }}
    state=latest
    enablerepo={{ repo_base_name }}
    with_items:
      - apr
      - apr-util
      - virt-what
      - pkgconfig

- name: Start Puppet Agent in noop mode
  copy:
    dest=/etc/sysconfig/pe-puppet
    content="EXTRA_OPTIONS=--noop"

- name: Ensure Puppet Agent is installed
  command: /root/puppetinstall/puppet-enterprise-{{ puppet_agent_version }}-all/puppet-enterprise-installer -a /root/puppetinstall/puppetagent.answers | tee /root/puppetinstall/puppetagentinstall.log


