---
# Ansible playbook to deploy Puppet Agent on a server and ensure its running
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Puppet Agent is started in noop mode
  copy:
    dest=/etc/sysconfig/pe-puppet
    content="EXTRA_OPTIONS=--noop"

- include: Redhat.yml
  when: ansible_os_family=="RedHat"

- include: Ubuntu.yml
  when: ansible_os_family=="Ubuntu"

- include: Debian.yml
  when: ansible_os_family=="Debian"

- include: AIX.yml
  when: ansible_os_family=="AIX"

- name: Start Puppet run to create and submit the cert
  command: puppet agent --test --waitforcert 300

- name: Accept the cert request on the PuppetMaster
  command: puppet cert sign {{ ansible_hostname }}
  delegate_to: "{{ puppetmaster_hostname }}"

- name: Ensure Puppet Agent is started
  command: puppet resource service puppet ensure=running enable=true

